/*
* Generated file
*
* Generated from: yang module name: lfm-ms-cassandradb yang module local name: lfm-ms-cassandradb
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jul 15 23:03:19 IST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.lfm.ms.dao.cassandradb;
public class CassandradbModuleFactory extends org.opendaylight.controller.config.yang.config.lfm.ms.dao.cassandradb.AbstractCassandradbModuleFactory {

}
